language: cpp
sudo: required
dist: trusty
git:
  submodules: true
      
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6 gcc-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo aptitude -f install  -y qt58base qt58serialport qt58script qt58svg qt58tools libusb-1.0-0-dev tree
 # - sudo apt-get install -qq -y qt57base qt57declarative qt57imageformats qt57location qt57multimedia qt57quickcontrols qt57script qt57svg qt57tools qt57translations libsdl2-dev
  
install:
    
  - source /opt/qt58/bin/qt58-env.sh
  
  
  - # Install libLua5.3  
  - # on newer ubuntu machines executing:  `sudo aptitude -f install liblua5.3-dev` should be enough
  - wget http://ftp.us.debian.org/debian/pool/main/l/lua5.3/liblua5.3-0_5.3.3-1_amd64.deb
  - wget http://ftp.br.debian.org/debian/pool/main/l/lua5.3/liblua5.3-dev_5.3.3-1_amd64.deb
  #- dpkg -c liblua5.3-0_5.3.3-1_amd64.deb
  - sudo dpkg -i liblua5.3-0_5.3.3-1_amd64.deb
  - sudo dpkg -i liblua5.3-dev_5.3.3-1_amd64.deb
  - ls /usr/lib/x86_64-linux-gnu/ | grep lua
  - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
    
    
    
    
  - #install gtest and gmock
  - cd $TRAVIS_BUILD_DIR/libs/googletest/
  - mkdir build || true
  - mkdir build/googletest || true
  - cd build/googletest
  - cmake -DCMAKE_CXX_FLAGS=$CXX_FLAGS \
          ../../
      
 # - export GTEST_TARGET=googletest 
#  - cd $TRAVIS_BUILD_DIR/libs/googletest
 # - ./travis.sh
 # - LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/libs/googletest/build/$GTEST_TARGET:$LD_LIBRARY_PATH
 # - export GTEST_TARGET=googlemock 
 # - cd $TRAVIS_BUILD_DIR/libs/googletest
#  - ./travis.sh
  - LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/libs/googletest/build/googletest:$LD_LIBRARY_PATH

  
  

  
  
  
  
  - # Install QWT
  - # on machines with qt5 executing:  `sudo aptitude -f install libqwt-dev` should be enough
 # - svn checkout svn://svn.code.sf.net/p/qwt/code/branches/qwt-6.1 qwt
  - git clone https://github.com/Crystal-Photonics/qwt
  - cd qwt
  - cp $TRAVIS_BUILD_DIR/libs/qwt/travis_qwtconfig.pri qwtconfig.pri
  - QWT_ROOT_DIR=`pwd`
  - LD_LIBRARY_PATH=$(readlink -f lib):$LD_LIBRARY_PATH
  - qmake
  - make -j$(nproc)
  - sudo make install
  #defined in travis_qwtconfig.pri
  - export CPATH=/usr/local/qwt-svn/include:$CPATH
  


script:
 # - source /opt/qt58/bin/qt58-env.sh
 #build limereport
  - ls 
  - cd $TRAVIS_BUILD_DIR
  - cd libs/LimeReport/
  - ls 
  - qmake
  - make -j$(nproc)
  #- tree -d build/
#build testframework  
  - cd $TRAVIS_BUILD_DIR
  - qmake
  - make -j$(nproc)
  
  
#notifications:
#irc:
#    channels:
#      - "chat.freenode.net#phoenix-dev"
#    use_notice: true
#    skip_join: true